# @package _global_

model:
  type: VPOcc
  embed_dims: 128
  view_scales: [4, 8, 16]
  scene_size: [256, 256, 32]
  volume_scale: 2
  num_classes: 19
  image_shape: [376, 1408]
  voxel_size: 0.2
  downsample_z: 2

  encoder:
    type: MMDetWrapper
    config_path: maskdino/configs/maskdino_r50_8xb2-panoptic-export.py
    custom_imports: maskdino
    checkpoint_path: ./backups/maskdino_r50_50e_300q_panoptic_pq53.0.pth
  criterions: [ce_ssc, sem_scal, geo_scal]

optimizer:
  paramwise_cfg:
    - name: encoder.model
      lr_mult: 0.1